### ISSUE TITLE
There's two folders with slightly different names but almost the same contents that have been diverging since 2017

### ISSUE THREAD

**Issue by lukebryant** [networklocum/prometheus-django#5]
Hey @rephus, was this just an accident or was there some reason it's like this?

**Comment by rephus** [comment]
this module was initially using `prometheus-django` but this naming is not a standard in python modules, so I made `prometheus_django` and kept `prometheus-django` for backwards compatibility, given the large amount of services that were already using this middleware.

But I don't think this is longer needed, so you could remove `prometheus-django` if you like.

**Comment by Lexicality** [comment]
mostly resolved by #7
